### ISSUE TITLE
resigning trophies for devkits and testkits must respect 3 conditions, and 1 is failing

### ISSUE THREAD

**Issue by zecoxao** [harlequin/ps4tools#1]
np_comm_id must be AAAA00000_00 (ok here)
resigning must be made by decrypting with retail key and encrypting with debug key (not respected here)
trophy must be named trophy00.trp (user can choose, so it's ok here)

i suggest before encrypting with retail key to encrypt with debug key and test. i can provide builds of debug trophy and retail trophy of a game for further analysis

edit: Here's the respective trophy files from minecraft retail and debug https://www.sendspace.com/file/yref00

**Comment by harlequin** [comment]
Resolve issue #1 with help from pull request
